### ISSUE TITLE
trzeba działąć #2

### ISSUE THREAD

**Issue by DorotaPawlowska** [dunk111/projekt_zespolowy#4]
musimy jak najbardziej skupić się na edytowaniu/commitowaniu tego projektu
dodajemy swoje kawałki tekstu poprawiamy swoje i innych akapity, 
pracujemy na wynik ;D

**Comment by DamianBlochowiak** [comment]
Moim zdaniem mimo że aplikacja jest mobilana musimy określić wszystkie elementy systemu ponieważ później łatwiej będzie nam zrozumię jak ona działa. A pozatym każda aplikacja ma jakiś użytkowników którzy z niej korzystają oraz którzy uzupełniają dane w aplikacji.

**Comment by dunk111** [comment]
wiecie dlaczego jak commitowalam plik to zrobil sie dodatkowy ~$ ? 

Dorota napisała :) - może da się usunąć te pliki binarne? ich i tak bez pobrania nie da się przejrzeć...

**Comment by DorotaPawlowska** [comment]
okej, dodatkowy opis nigdy nie zawadzi ale teraz nie ma tego właściwego dotyczącego samej aplikacji.
jest tylko szczegółowy opis systemu biblioteki a gdzie w tym wszystki użytkownik telefonu?
wydaje mi się że aplikacja na telefon to nie to samo co adres strony internetowej do zalogowania?

**Comment by dunk111** [comment]
piliki binarne usuniete :) opis mój rozbudowałam, czegoś jeszcze brakuje, coś byście dodali ?? :)

**Comment by DorotaPawlowska** [comment]
no ja jedynie chciałabym żeby Damian sam dodał swój kawałek tesktu do reszty bo nie będziemy odbierać mu przecież aktywności commitowej :D

**Comment by dunk111** [comment]
doda doda :d Damian haloooooo jestes tuuu ? :mailbox:

**Comment by DorotaPawlowska** [comment]
jakby co to ja jestem na stendbaju :)

**Comment by DamianBlochowiak** [comment]
jestem zaraz dodam swój tekst
